name: Passwordstore action
description: Make secrets from your passwordstore.org repository available to your job as environment variables
inputs:
  private_key:
    description: 'Private PGP key'
    required: true
  passphrase:
    description: 'Passphrase for private PGP key'
    required: false
  repository:
    description: 'Password store repository'
    required: true
runs:
  using: docker
  image: Dockerfile
branding:
  icon: lock
  color: blue
